name: Generate new release
on:
  push:
    tags:
      - 'v2*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: main
      - name: Use Node.js 18.x 🪢
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - run: sudo apt-get update && sudo apt-get install -y zip
      - run: npm ci
      - run: npm run build
      - run: npm i extract-changelog-release
      - name: Generate Release Body
        run: npx extract-changelog-release > RELEASE_BODY.md
      - run: sh ./scripts/create-release-attachment.sh
      - uses: ncipollo/release-action@v1
        with:
          artifacts: './dist/zip/*.zip'
          bodyFile: 'RELEASE_BODY.md'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish on gh-pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run documentation-deploy-to-gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}